import { AgentBlock, BlockParameter } from '@/types/agent-builder';

export const BLOCK_CATEGORIES = [
  'All',
  'Triggers',
  'Conditions',
  'Actions',
  'Data',
  'AI',
  'Integrations',
] as const;

export type BlockCategory = typeof BLOCK_CATEGORIES[number];

export interface BlockTemplate {
  type: string;
  label: string;
  description: string;
  category: BlockCategory;
  icon: string;
  defaultData: Record<string, any>;
  defaultParameters?: BlockParameter[];
  color?: string;
  inputs?: number;
  outputs?: number;
}

export const BLOCK_TEMPLATES: BlockTemplate[] = [
  // Triggers
  {
    type: 'trigger_price',
    label: 'Price Trigger',
    description: 'Trigger when asset reaches a specific price',
    category: 'Triggers',
    icon: 'DollarSign',
    color: '#10b981',
    defaultData: {
      asset: 'XLM',
      condition: 'above',
      price: 0,
    },
    defaultParameters: [
      {
        id: 'param_1',
        name: 'asset',
        type: 'select',
        value: 'XLM',
        required: true,
        description: 'The asset to monitor',
        options: ['XLM', 'USDC', 'BTC', 'ETH'],
      },
      {
        id: 'param_2',
        name: 'condition',
        type: 'select',
        value: 'above',
        required: true,
        description: 'Price condition',
        options: ['above', 'below', 'equals'],
      },
      {
        id: 'param_3',
        name: 'price',
        type: 'number',
        value: 0,
        required: true,
        placeholder: 'Enter target price',
        description: 'Target price to trigger at',
        min: 0,
        step: 0.01,
      },
    ],
    inputs: 0,
    outputs: 1,
  },
  {
    type: 'trigger_time',
    label: 'Time Trigger',
    description: 'Trigger at specific time intervals',
    category: 'Triggers',
    icon: 'Clock',
    color: '#3b82f6',
    defaultData: {
      interval: '1h',
      enabled: true,
    },
    inputs: 0,
    outputs: 1,
  },
  {
    type: 'trigger_indicator',
    label: 'Indicator Trigger',
    description: 'Trigger based on technical indicators',
    category: 'Triggers',
    icon: 'TrendingUp',
    color: '#8b5cf6',
    defaultData: {
      indicator: 'RSI',
      condition: 'above',
      value: 70,
    },
    inputs: 0,
    outputs: 1,
  },

  // Conditions
  {
    type: 'condition_compare',
    label: 'Compare',
    description: 'Compare two values',
    category: 'Conditions',
    icon: 'GitCompare',
    color: '#f59e0b',
    defaultData: {
      operator: 'greater_than',
      valueA: 0,
      valueB: 0,
    },
    inputs: 1,
    outputs: 2,
  },
  {
    type: 'condition_and',
    label: 'AND Gate',
    description: 'All conditions must be true',
    category: 'Conditions',
    icon: 'GitMerge',
    color: '#06b6d4',
    defaultData: {},
    inputs: 2,
    outputs: 1,
  },
  {
    type: 'condition_or',
    label: 'OR Gate',
    description: 'At least one condition must be true',
    category: 'Conditions',
    icon: 'GitBranch',
    color: '#14b8a6',
    defaultData: {},
    inputs: 2,
    outputs: 1,
  },

  // Actions
  {
    type: 'action_buy',
    label: 'Buy Order',
    description: 'Execute a buy order',
    category: 'Actions',
    icon: 'TrendingUp',
    color: '#10b981',
    defaultData: {
      asset: 'XLM',
      amount: 0,
      orderType: 'market',
    },
    defaultParameters: [
      {
        id: 'param_1',
        name: 'asset',
        type: 'select',
        value: 'XLM',
        required: true,
        description: 'The asset to buy',
        options: ['XLM', 'USDC', 'BTC', 'ETH'],
      },
      {
        id: 'param_2',
        name: 'amount',
        type: 'number',
        value: 0,
        required: true,
        placeholder: 'Enter amount',
        description: 'Amount to buy',
        min: 0,
        step: 0.01,
      },
      {
        id: 'param_3',
        name: 'orderType',
        type: 'select',
        value: 'market',
        required: true,
        description: 'Type of order',
        options: ['market', 'limit'],
      },
    ],
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'action_sell',
    label: 'Sell Order',
    description: 'Execute a sell order',
    category: 'Actions',
    icon: 'TrendingDown',
    color: '#ef4444',
    defaultData: {
      asset: 'XLM',
      amount: 0,
      orderType: 'market',
    },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'action_swap',
    label: 'Swap Assets',
    description: 'Swap between two assets',
    category: 'Actions',
    icon: 'ArrowLeftRight',
    color: '#6366f1',
    defaultData: {
      fromAsset: 'XLM',
      toAsset: 'USDC',
      amount: 0,
    },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'action_notify',
    label: 'Send Notification',
    description: 'Send a notification or alert',
    category: 'Actions',
    icon: 'Bell',
    color: '#f59e0b',
    defaultData: {
      message: '',
      channel: 'email',
    },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'action_transfer',
    label: 'Transfer XLM',
    description: 'Transfer XLM to an address using Quantum Wallet',
    category: 'Actions',
    icon: 'Send',
    color: '#ffd700',
    defaultData: {
      destinationAddress: '',
      amount: '0',
      token: 'XLM',
    },
    defaultParameters: [
      {
        id: 'param_dest',
        name: 'destinationAddress',
        type: 'text',
        value: '',
        required: true,
        placeholder: 'G...',
        description: 'Stellar address to send to',
      },
      {
        id: 'param_amount',
        name: 'amount',
        type: 'text',
        value: '0',
        required: true,
        placeholder: '10',
        description: 'Amount to transfer',
      },
      {
        id: 'param_token',
        name: 'token',
        type: 'select',
        value: 'XLM',
        required: true,
        description: 'Token to transfer',
        options: ['XLM'],
      },
    ],
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'action_multi_send',
    label: 'Multi-Send',
    description: 'Send XLM to multiple recipients in one transaction',
    category: 'Actions',
    icon: 'Users',
    color: '#22c55e',
    defaultData: {
      recipients: [],
      memo: '',
    },
    defaultParameters: [
      {
        id: 'param_recipients',
        name: 'recipients',
        type: 'text',
        value: '',
        required: true,
        placeholder: 'GADDR1:10,GADDR2:20',
        description: 'Recipients as ADDRESS:AMOUNT pairs (comma-separated)',
      },
      {
        id: 'param_memo',
        name: 'memo',
        type: 'text',
        value: '',
        required: false,
        placeholder: 'Batch payment',
        description: 'Optional transaction memo',
      },
    ],
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'action_webhook',
    label: 'Webhook',
    description: 'Send HTTP POST notification to a URL',
    category: 'Actions',
    icon: 'Webhook',
    color: '#ec4899',
    defaultData: {
      url: '',
      payload: {},
    },
    defaultParameters: [
      {
        id: 'param_url',
        name: 'url',
        type: 'text',
        value: '',
        required: true,
        placeholder: 'https://webhook.site/...',
        description: 'Webhook URL to POST to',
      },
      {
        id: 'param_payload',
        name: 'payload',
        type: 'text',
        value: '{}',
        required: false,
        placeholder: '{"key": "value"}',
        description: 'JSON payload to send',
      },
    ],
    inputs: 1,
    outputs: 1,
  },

  // Data
  {
    type: 'data_fetch_price',
    label: 'Fetch Price',
    description: 'Get current price of an asset',
    category: 'Data',
    icon: 'Database',
    color: '#8b5cf6',
    defaultData: {
      asset: 'XLM',
      source: 'stellar',
    },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'data_calculate',
    label: 'Calculate',
    description: 'Perform mathematical calculations',
    category: 'Data',
    icon: 'Calculator',
    color: '#06b6d4',
    defaultData: {
      operation: 'add',
      valueA: 0,
      valueB: 0,
    },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'data_variable',
    label: 'Variable',
    description: 'Store and retrieve data',
    category: 'Data',
    icon: 'Box',
    color: '#64748b',
    defaultData: {
      name: 'variable1',
      value: null,
    },
    inputs: 1,
    outputs: 1,
  },

  // Integrations
  {
    type: 'integration_stellar',
    label: 'Stellar Network',
    description: 'Interact with Stellar blockchain',
    category: 'Integrations',
    icon: 'Network',
    color: '#3b82f6',
    defaultData: {
      network: 'testnet',
      operation: 'payment',
    },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'integration_webhook',
    label: 'Webhook',
    description: 'Send data to external endpoint',
    category: 'Integrations',
    icon: 'Webhook',
    color: '#8b5cf6',
    defaultData: {
      url: '',
      method: 'POST',
    },
    inputs: 1,
    outputs: 1,
  },

  // AI Category - Smart Trading Blocks
  {
    type: 'ai_strategy',
    label: 'AI Trading Strategy',
    description: 'AI-powered trading decisions based on market data',
    category: 'AI',
    icon: 'Brain',
    color: '#ec4899',
    defaultData: {
      strategy: 'momentum',
      riskLevel: 'medium',
      signal: null,
      confidence: 0,
    },
    defaultParameters: [
      {
        id: 'param_strategy',
        name: 'strategy',
        type: 'select',
        value: 'momentum',
        required: true,
        description: 'AI trading strategy to use',
        options: ['momentum', 'mean_reversion', 'breakout', 'sentiment', 'ml_ensemble'],
      },
      {
        id: 'param_risk',
        name: 'riskLevel',
        type: 'select',
        value: 'medium',
        required: true,
        description: 'Risk tolerance level',
        options: ['conservative', 'medium', 'aggressive'],
      },
      {
        id: 'param_pair',
        name: 'tradingPair',
        type: 'select',
        value: 'XLM/USDC',
        required: true,
        description: 'Trading pair to analyze',
        options: ['XLM/USDC', 'XLM/BTC', 'USDC/XLM', 'yXLM/XLM'],
      },
      {
        id: 'param_timeframe',
        name: 'timeframe',
        type: 'select',
        value: '1h',
        required: true,
        description: 'Analysis timeframe',
        options: ['5m', '15m', '1h', '4h', '1d'],
      },
    ],
    inputs: 1,
    outputs: 3, // buy, sell, hold outputs
  },
  {
    type: 'ai_sentiment',
    label: 'Market Sentiment',
    description: 'AI analysis of market sentiment from multiple sources',
    category: 'AI',
    icon: 'Activity',
    color: '#f472b6',
    defaultData: {
      sentimentScore: 0,
      sources: ['orderbook', 'volume', 'price_action'],
    },
    defaultParameters: [
      {
        id: 'param_asset',
        name: 'asset',
        type: 'select',
        value: 'XLM',
        required: true,
        description: 'Asset to analyze',
        options: ['XLM', 'USDC', 'yUSDC', 'AQUA'],
      },
      {
        id: 'param_sensitivity',
        name: 'sensitivity',
        type: 'select',
        value: 'medium',
        required: true,
        description: 'Sentiment sensitivity',
        options: ['low', 'medium', 'high'],
      },
    ],
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'ai_risk_manager',
    label: 'AI Risk Manager',
    description: 'Intelligent position sizing and risk management',
    category: 'AI',
    icon: 'Shield',
    color: '#a855f7',
    defaultData: {
      maxPositionSize: 10,
      stopLossPercent: 5,
      takeProfitPercent: 10,
    },
    defaultParameters: [
      {
        id: 'param_max_position',
        name: 'maxPositionSize',
        type: 'percentage',
        value: 10,
        required: true,
        description: 'Max position size (% of portfolio)',
        min: 1,
        max: 100,
      },
      {
        id: 'param_stop_loss',
        name: 'stopLossPercent',
        type: 'number',
        value: 5,
        required: true,
        description: 'Stop loss percentage',
        min: 0.5,
        max: 50,
        step: 0.5,
      },
      {
        id: 'param_take_profit',
        name: 'takeProfitPercent',
        type: 'number',
        value: 10,
        required: true,
        description: 'Take profit percentage',
        min: 1,
        max: 100,
        step: 0.5,
      },
    ],
    inputs: 1,
    outputs: 1,
  },

  // Enhanced Data Blocks for Trading
  {
    type: 'data_ohlcv',
    label: 'Market OHLCV',
    description: 'Fetch candlestick data (Open, High, Low, Close, Volume)',
    category: 'Data',
    icon: 'BarChart3',
    color: '#0ea5e9',
    defaultData: {
      pair: 'XLM/USDC',
      timeframe: '1h',
      limit: 100,
    },
    defaultParameters: [
      {
        id: 'param_pair',
        name: 'pair',
        type: 'select',
        value: 'XLM/USDC',
        required: true,
        description: 'Trading pair',
        options: ['XLM/USDC', 'XLM/BTC', 'USDC/XLM', 'yXLM/XLM'],
      },
      {
        id: 'param_timeframe',
        name: 'timeframe',
        type: 'select',
        value: '1h',
        required: true,
        description: 'Candle timeframe',
        options: ['1m', '5m', '15m', '1h', '4h', '1d', '1w'],
      },
      {
        id: 'param_limit',
        name: 'limit',
        type: 'number',
        value: 100,
        required: false,
        description: 'Number of candles to fetch',
        min: 10,
        max: 500,
        step: 10,
      },
    ],
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'data_orderbook',
    label: 'DEX Orderbook',
    description: 'Fetch live orderbook depth from Stellar DEX',
    category: 'Data',
    icon: 'List',
    color: '#22c55e',
    defaultData: {
      baseAsset: 'XLM',
      counterAsset: 'USDC',
      depth: 20,
    },
    defaultParameters: [
      {
        id: 'param_base',
        name: 'baseAsset',
        type: 'select',
        value: 'XLM',
        required: true,
        description: 'Base asset',
        options: ['XLM', 'USDC', 'yUSDC', 'AQUA', 'SRT'],
      },
      {
        id: 'param_counter',
        name: 'counterAsset',
        type: 'select',
        value: 'USDC',
        required: true,
        description: 'Counter asset',
        options: ['USDC', 'XLM', 'yUSDC', 'AQUA', 'SRT'],
      },
      {
        id: 'param_depth',
        name: 'depth',
        type: 'number',
        value: 20,
        required: false,
        description: 'Orderbook depth (number of levels)',
        min: 5,
        max: 100,
        step: 5,
      },
    ],
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'data_portfolio',
    label: 'Portfolio Balance',
    description: 'Get current portfolio balances and positions',
    category: 'Data',
    icon: 'Wallet',
    color: '#f59e0b',
    defaultData: {
      includeOffers: true,
      includeTrustlines: true,
    },
    defaultParameters: [
      {
        id: 'param_offers',
        name: 'includeOffers',
        type: 'boolean',
        value: true,
        required: false,
        description: 'Include open offers',
      },
      {
        id: 'param_trustlines',
        name: 'includeTrustlines',
        type: 'boolean',
        value: true,
        required: false,
        description: 'Include all trustlines',
      },
    ],
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'data_indicator',
    label: 'Technical Indicator',
    description: 'Calculate technical indicators (RSI, MACD, EMA, etc)',
    category: 'Data',
    icon: 'LineChart',
    color: '#6366f1',
    defaultData: {
      indicator: 'RSI',
      period: 14,
      source: 'close',
    },
    defaultParameters: [
      {
        id: 'param_indicator',
        name: 'indicator',
        type: 'select',
        value: 'RSI',
        required: true,
        description: 'Technical indicator',
        options: ['RSI', 'MACD', 'EMA', 'SMA', 'Bollinger', 'ATR', 'VWAP'],
      },
      {
        id: 'param_period',
        name: 'period',
        type: 'number',
        value: 14,
        required: true,
        description: 'Indicator period',
        min: 2,
        max: 200,
        step: 1,
      },
      {
        id: 'param_source',
        name: 'source',
        type: 'select',
        value: 'close',
        required: false,
        description: 'Price source',
        options: ['close', 'open', 'high', 'low', 'hl2', 'hlc3'],
      },
    ],
    inputs: 1,
    outputs: 1,
  },

  // DEX Trading Actions
  {
    type: 'action_dex_swap',
    label: 'DEX Swap',
    description: 'Execute a swap on Stellar DEX (testnet)',
    category: 'Actions',
    icon: 'Repeat',
    color: '#06b6d4',
    defaultData: {
      sourceAsset: 'XLM',
      destAsset: 'USDC',
      amount: '10',
      slippage: 0.5,
      swapType: 'exactIn',
    },
    defaultParameters: [
      {
        id: 'param_source',
        name: 'sourceAsset',
        type: 'select',
        value: 'XLM',
        required: true,
        description: 'Asset to sell',
        options: ['XLM', 'USDC', 'yUSDC', 'AQUA', 'SRT'],
      },
      {
        id: 'param_dest',
        name: 'destAsset',
        type: 'select',
        value: 'USDC',
        required: true,
        description: 'Asset to buy',
        options: ['USDC', 'XLM', 'yUSDC', 'AQUA', 'SRT'],
      },
      {
        id: 'param_amount',
        name: 'amount',
        type: 'text',
        value: '10',
        required: true,
        placeholder: '10',
        description: 'Amount to swap',
      },
      {
        id: 'param_slippage',
        name: 'slippage',
        type: 'number',
        value: 0.5,
        required: false,
        description: 'Max slippage %',
        min: 0.1,
        max: 10,
        step: 0.1,
      },
      {
        id: 'param_swap_type',
        name: 'swapType',
        type: 'select',
        value: 'exactIn',
        required: true,
        description: 'Swap type',
        options: ['exactIn', 'exactOut'],
      },
    ],
    inputs: 1,
    outputs: 2, // success, failure
  },
  {
    type: 'action_manage_offer',
    label: 'Manage Offer',
    description: 'Create, update, or cancel orderbook offers',
    category: 'Actions',
    icon: 'ScrollText',
    color: '#14b8a6',
    defaultData: {
      action: 'create',
      sellAsset: 'XLM',
      buyAsset: 'USDC',
      amount: '100',
      price: '0.10',
    },
    defaultParameters: [
      {
        id: 'param_action',
        name: 'action',
        type: 'select',
        value: 'create',
        required: true,
        description: 'Offer action',
        options: ['create', 'update', 'cancel'],
      },
      {
        id: 'param_sell',
        name: 'sellAsset',
        type: 'select',
        value: 'XLM',
        required: true,
        description: 'Asset to sell',
        options: ['XLM', 'USDC', 'yUSDC', 'AQUA'],
      },
      {
        id: 'param_buy',
        name: 'buyAsset',
        type: 'select',
        value: 'USDC',
        required: true,
        description: 'Asset to buy',
        options: ['USDC', 'XLM', 'yUSDC', 'AQUA'],
      },
      {
        id: 'param_amount',
        name: 'amount',
        type: 'text',
        value: '100',
        required: true,
        placeholder: '100',
        description: 'Amount to sell',
      },
      {
        id: 'param_price',
        name: 'price',
        type: 'text',
        value: '0.10',
        required: true,
        placeholder: '0.10',
        description: 'Price per unit',
      },
    ],
    inputs: 1,
    outputs: 2, // success, failure
  },
  {
    type: 'action_stop_loss',
    label: 'Stop Loss',
    description: 'Automatic stop loss order when price drops',
    category: 'Actions',
    icon: 'ShieldAlert',
    color: '#ef4444',
    defaultData: {
      asset: 'XLM',
      triggerPrice: '0.08',
      sellPercent: 100,
    },
    defaultParameters: [
      {
        id: 'param_asset',
        name: 'asset',
        type: 'select',
        value: 'XLM',
        required: true,
        description: 'Asset to protect',
        options: ['XLM', 'USDC', 'yUSDC', 'AQUA'],
      },
      {
        id: 'param_trigger',
        name: 'triggerPrice',
        type: 'text',
        value: '0.08',
        required: true,
        placeholder: '0.08',
        description: 'Trigger price',
      },
      {
        id: 'param_percent',
        name: 'sellPercent',
        type: 'percentage',
        value: 100,
        required: true,
        description: 'Percentage of holdings to sell',
        min: 1,
        max: 100,
      },
    ],
    inputs: 1,
    outputs: 2, // triggered, not triggered
  },
  {
    type: 'action_take_profit',
    label: 'Take Profit',
    description: 'Automatic profit taking when price rises',
    category: 'Actions',
    icon: 'Target',
    color: '#22c55e',
    defaultData: {
      asset: 'XLM',
      triggerPrice: '0.15',
      sellPercent: 50,
    },
    defaultParameters: [
      {
        id: 'param_asset',
        name: 'asset',
        type: 'select',
        value: 'XLM',
        required: true,
        description: 'Asset to sell',
        options: ['XLM', 'USDC', 'yUSDC', 'AQUA'],
      },
      {
        id: 'param_trigger',
        name: 'triggerPrice',
        type: 'text',
        value: '0.15',
        required: true,
        placeholder: '0.15',
        description: 'Trigger price',
      },
      {
        id: 'param_percent',
        name: 'sellPercent',
        type: 'percentage',
        value: 50,
        required: true,
        description: 'Percentage to sell',
        min: 1,
        max: 100,
      },
    ],
    inputs: 1,
    outputs: 2, // triggered, not triggered
  },

  // Enhanced Triggers
  {
    type: 'trigger_interval',
    label: 'Interval Timer',
    description: 'Trigger at regular intervals for automated trading',
    category: 'Triggers',
    icon: 'Timer',
    color: '#f97316',
    defaultData: {
      interval: '5m',
      runImmediately: true,
    },
    defaultParameters: [
      {
        id: 'param_interval',
        name: 'interval',
        type: 'select',
        value: '5m',
        required: true,
        description: 'Execution interval',
        options: ['1m', '5m', '15m', '30m', '1h', '4h', '1d'],
      },
      {
        id: 'param_immediate',
        name: 'runImmediately',
        type: 'boolean',
        value: true,
        required: false,
        description: 'Run immediately on start',
      },
    ],
    inputs: 0,
    outputs: 1,
  },
  {
    type: 'trigger_orderbook',
    label: 'Orderbook Trigger',
    description: 'Trigger on orderbook changes (spread, depth, imbalance)',
    category: 'Triggers',
    icon: 'Layers',
    color: '#84cc16',
    defaultData: {
      pair: 'XLM/USDC',
      condition: 'spread_below',
      value: 0.5,
    },
    defaultParameters: [
      {
        id: 'param_pair',
        name: 'pair',
        type: 'select',
        value: 'XLM/USDC',
        required: true,
        description: 'Trading pair to monitor',
        options: ['XLM/USDC', 'XLM/BTC', 'USDC/XLM'],
      },
      {
        id: 'param_condition',
        name: 'condition',
        type: 'select',
        value: 'spread_below',
        required: true,
        description: 'Orderbook condition',
        options: ['spread_below', 'spread_above', 'bid_imbalance', 'ask_imbalance', 'depth_change'],
      },
      {
        id: 'param_value',
        name: 'value',
        type: 'number',
        value: 0.5,
        required: true,
        description: 'Threshold value (%)',
        min: 0.01,
        max: 100,
        step: 0.01,
      },
    ],
    inputs: 0,
    outputs: 1,
  },
];

export function getBlockTemplate(type: string): BlockTemplate | undefined {
  return BLOCK_TEMPLATES.find(t => t.type === type);
}

export function getBlocksByCategory(category: BlockCategory): BlockTemplate[] {
  if (category === 'All') return BLOCK_TEMPLATES;
  return BLOCK_TEMPLATES.filter(t => t.category === category);
}
