import LenisProvider from '@/src/providers/LenisProvider';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Nebula',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased bg-black`} suppressHydrationWarning>
                <LenisProvider>{children}</LenisProvider>
            </body>
        </html>
    );
}
