export enum ClientDocsPanel {
    OVERVIEW = 'OVERVIEW',
    GETTING_STARTED = 'GETTING_STARTED',
    WINTER_SHELL = 'WINTER_SHELL',
    DEPLOYMENT = 'DEPLOYMENT',
    EXPORTING = 'EXPORTING',
    SANDBOX = 'SANDBOX',
    SANDBOX_INTRO = 'SANDBOX_INTRO',
    SANDBOX_CONFIGURATION = 'SANDBOX_CONFIGURATION',
    SANDBOX_USAGE = 'SANDBOX_USAGE',
}

export enum OverviewSubContent {
    AI_CONTRACTS = 'AI_CONTRACTS',
    SMART_EDITOR = 'SMART_EDITOR',
    ONE_CLICK_DEPLOYMENT = 'ONE_CLICK_DEPLOYMENT',
}

export enum GettingStartedSubContent {
    CREATE_ACCOUNT = 'CREATE_ACCOUNT',
    FIRST_PROMPT = 'FIRST_PROMPT',
    PLAYGROUND_OVERVIEW = 'PLAYGROUND_OVERVIEW',
    UPDATE_CONTRACT = 'UPDATE_CONTRACT',
    WINTER_SHELL = 'WINTER_SHELL',
    EXPORT_CONTRACT = 'EXPORT_CONTRACT',
}

// first prompt -> playground page overview -> update contract -> winter shell -> export

export enum SandboxSubContent {
    OVERVIEW = 'OVERVIEW',
    FEATURES = 'FEATURES',
    SECURITY = 'SECURITY',
    DEPLOY = 'DEPLOY',
}

export enum WinterShellSubContent {
    WINTER_SHELL_INFO = 'WINTER_SHELL_INFO',
    TEST_CONTRACT = 'TEST_CONTRACT',
    BUILD_CONTRACT = 'BUILD_CONTRACT',
    DEPLOY_CONTRACT = 'DEPLOY_CONTRACT',
}

export enum DeploymentSubContent {
    DEPLOYMENT_INFO = 'DEPLOYMENT_INFO',
    DEPLOYMENT_REQUIREMENTS = 'DEPLOYMENT_REQUIREMENTS',
    DEPLOYMENT_NETWORKS = 'DEPLOYMENT_NETWORKS',
}

export enum ExportingSubContent {
    EXPORTING_INFO = 'EXPORTING_INFO',
    EXPORTING_OPTIONS = 'EXPORTING_OPTIONS',
    CONNECT_GITHUB = 'CONNECT_GITHUB',
    EXPORT_REQUIREMENTS = 'EXPORT_REQUIREMENTS',
}
