import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import SessionSetter from '@/src/lib/SessionSeter';
import { authOption } from '@/app/api/auth/[...nextauth]/options';
import { Toaster } from 'sonner';

interface Props {
    children: React.ReactNode;
}

export const metadata: Metadata = {
    title: 'Nebula',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Props) {
    const session = await getServerSession(authOption);

    return (
        <html lang="en">
            <body
                className={`flex h-screen w-screen items-center justify-center bg-neutral-900`}
                suppressHydrationWarning
            >
                {children}
                <Toaster
                    theme="dark"
                    closeButton
                    visibleToasts={4}
                    toastOptions={{
                        style: {
                            background: '#0c0d0e',
                            color: '#FFFFFF',
                            border: '1px solid #2C2C2E',
                            borderRadius: '12px',
                            boxShadow: '0 4px 16px rgba(0, 0, 0, 0.6)',
                        },
                        classNames: {
                            title: 'text-white font-semibold',
                            description: 'text-gray-300',
                            actionButton: 'bg-indigo-600 text-white hover:bg-indigo-700',
                            cancelButton: 'bg-gray-700 text-white hover:bg-gray-800',
                        },
                    }}
                />
                <SessionSetter session={session} />
            </body>
        </html>
    );
}
